// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniformShop.Models;

namespace UniformShop.Migrations
{
    [DbContext(typeof(UniformShopContext))]
    partial class UniformShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniformShop.Models.Customer", b =>
                {
                    b.Property<long>("custId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<long?>("cardNumber");

                    b.Property<string>("custName");

                    b.Property<string>("email");

                    b.Property<bool?>("notifications");

                    b.Property<string>("password");

                    b.Property<string>("phone");

                    b.Property<string>("userName");

                    b.HasKey("custId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
